services:
    postgres:
        image: timescale/timescaledb:latest-pg15
        container_name: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        networks:
            - stack-network
        restart: always

    worker:
        build:
            context: ../
            dockerfile: deploy/worker/Dockerfile
        container_name: worker
        depends_on:
            - postgres
        networks:
            - stack-network
        restart: always
        environment:
          DATABASE_URL: ${DATABASE_URL}
          VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
          VAPID_MAILTO: ${VAPID_MAILTO}

    rest-api:
        build:
            context: ../
            dockerfile: deploy/rest-api/Dockerfile
        container_name: rest-api
        restart: always
        depends_on:
            - postgres
        networks:
            - stack-network
        environment:
            DATABASE_URL: ${DATABASE_URL}
            CLERK_URL: ${CLERK_URL}
            LISTEN_PORT: ${LISTEN_PORT}
            CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
            VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}

    loki:
        image: grafana/loki:3.0.0
        container_name: loki
        command: -config.file=/etc/loki/local-config.yaml
        volumes:
          - ./loki-data:/loki
        networks:
          - stack-network

    grafana:
        image: grafana/grafana:10.4.0
        container_name: grafana
        environment:
            GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
            GF_ANALYTICS_REPORTING_ENABLED: false
        volumes:
          - ./grafana-data:/var/lib/grafana
        networks:
          - stack-network
        depends_on:
          - loki

    frontend:
        build:
            context: ../
            dockerfile: deploy/frontend/Dockerfile
            args:
                VITE_API_URL: ${VITE_API_URL}
                VITE_CLERK_PUBLISHABLE_KEY: ${VITE_CLERK_PUBLISHABLE_KEY}
        container_name: frontend
        restart: always
        depends_on:
            - rest-api

networks:
    stack-network:
        driver: bridge

# to connect with CLI docker exec -it mineccraft-stats-postgres psql -U anuser -d minecraft-stats