[package]
name = "worker"
version = "0.1.0"
edition = "2024"

[dependencies]
minecraft-pinger = { workspace = true }
repository = { workspace = true }

log = { workspace = true }
env_logger = { workspace = true }

tokio = { workspace = true }
futures = { workspace = true }

serde_json = { workspace = true }

time = { workspace = true }
openssl = { workspace = true }

web-push = { workspace = true }